### ISSUE TITLE
Error while running `pcicrawler` utility

### ISSUE THREAD

**Issue by gabhijit** [facebookincubator/pcicrawler#3]
While running the `pcicrawler` utility from within a virtual-environment - Following `ModuleNotFound` error is observed - 

```shell
(venv) gabhijit@gabhijit-GL553VD:~/backup/personal-code/pcicrawler$ pcicrawler
Traceback (most recent call last):
  File "/home/gabhijit/backup/personal-code/pcicrawler/venv/bin/pcicrawler", line 11, in <module>
    load_entry_point('pcicrawler==0.1.0', 'console_scripts', 'pcicrawler')()
  File "/home/gabhijit/backup/personal-code/pcicrawler/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/gabhijit/backup/personal-code/pcicrawler/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/home/gabhijit/backup/personal-code/pcicrawler/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/home/gabhijit/backup/personal-code/pcicrawler/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/gabhijit/backup/personal-code/pcicrawler/venv/lib/python3.7/site-packages/pcicrawler-0.1.0-py3.7.egg/pcicrawler/cli.py", line 12, in <module>
ModuleNotFoundError: No module named 'pcicrawler.lib'
```

Indeed there is no module named `lib` inside `pcicrawler`.

This error is observed while running from the checked out repo after doing a `setup.py install` in virtualenv.

**Comment by gabhijit** [comment]
Likely the entire `lib` directory is missed to be checked in?

**Comment by mmlcbr** [comment]
Thanks for raising the issue. Currently working on removing the reference to `pcicrawler.lib`.

**Comment by gabhijit** [comment]
Okay! created a pull request with the fix.

**Comment by gabhijit** [comment]
@martinezmarcos  I see that you have removed the reference to `pcicrawler.lib` so the 'master' branch now works. Closing this issue, however having this hard coded return value of 16 is a really bad idea and totally avoidable! 

I also, see there is only one place where there is explicit `sys.exit` with an error code. Also using `1` or `-1` makes more sense for this particular case because _semantically_ it is correct.
```bash
$ errno -l | grep EPERM
EPERM 1 Operation not permitted
```

**Comment by mmlcbr** [comment]
@gabhijit Thanks for your helpful insight. We will definitely consider the suggestions offered when working on this. For now, removing the reference was the intention. Hope you find the tool helpful and we encourage further contribution!
